services:
  # web:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.dev 
  #   volumes:
  #     - .:/app                        # ← mount current folder to /app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=postgresql://jyotsna:password@ecom-db:5432/ecommerce
  #     - JWT_SECRET=your_jwt_secret_here
  #   depends_on:
  #     - ecom-db

  ecom-db:
    image: postgres:16
    environment:
      POSTGRES_USER: jyotsna
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data

volumes:
  pgdata1:
