apiVersion: v1
kind: Service
metadata:
  name: ecommerce-web-service
  namespace: ecommerce
spec:
  selector:
    app: ecommerce-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer